### ISSUE TITLE
about the support set

### ISSUE THREAD

**Issue by Devil-Ideal** [cnulab/MediCLIP#7]
Hi! Thank you for your excellent work. I'm not very familiar with few-shot anomaly detection. I was wondering if using only a few normal images and synthesizing abnormal ones instead of using true abnormal samples directly, is intend to ensure diversity.

**Comment by cnulab** [comment]
Hello, this is to simulate the real-world scenario where it is difficult to collect abnormal samples from certain areas. The experiment was conducted under the most strictest conditions, where abnormal samples were not available. If real anomalous samples are accessible, the synthesized anomalies can be combined with real anomalies to further improve performance.

**Comment by Devil-Ideal** [comment]
> Hello, this is to simulate the real-world scenario where it is difficult to collect abnormal samples from certain areas. The experiment was conducted under the most strictest conditions, where abnormal samples were not available. If real anomalous samples are accessible, the synthesized anomalies can be combined with real anomalies to further improve performance.

thank you for reply
